export type ProductPresentation = {
  label: string;
  benefit: string;
  featureDescriptions: string[];
  screens: [{ title: string; description: string }, { title: string; description: string }];
};

const presentations: Record<string, ProductPresentation> = {
  atlas: { label: "Sistema para oficinas", benefit: "Acompanhe cada veículo, atendimento e próxima ação sem perder o histórico.", featureDescriptions: ["Visualize as ordens por etapa e identifique o que precisa avançar.", "Registre o relato do cliente, a avaliação da oficina e a conclusão técnica.", "Mantenha fotos e observações vinculadas ao atendimento correto.", "Acompanhe aprovação, execução, agendamento e entrega sem misturar informações."], screens: [{ title: "Operação da oficina", description: "Ordens de serviço, veículos e próximas ações organizados para o atendimento diário." }, { title: "Detalhe técnico da OS", description: "Diagnóstico, orçamento, evidências e histórico reunidos no mesmo atendimento." }] },
  zeus: { label: "Gestão de frotas", benefit: "Organize veículos, motoristas, documentos e manutenções em uma visão direta.", featureDescriptions: ["Consulte situação, quilometragem e responsável por cada veículo.", "Acompanhe manutenções preventivas sem depender de controles dispersos.", "Mantenha motorista e veículo com situações coerentes entre si.", "Registre abastecimentos e ocorrências para preservar o histórico da frota."], screens: [{ title: "Garagem da frota", description: "Consulte disponibilidade, responsável e condição de cada veículo." }, { title: "Histórico do veículo", description: "Manutenções, documentos e ocorrências preservados em uma ficha única." }] },
  artemis: { label: "Sistema para restaurantes", benefit: "Conecte salão, comandas e cozinha em um fluxo simples de atendimento.", featureDescriptions: ["Veja mesas livres, ocupadas, na cozinha ou prontas para servir.", "Adicione itens, quantidades e observações diretamente na comanda.", "Envie pedidos e acompanhe cada etapa da fila de preparo.", "Edite disponibilidade, categorias e preços do cardápio."], screens: [{ title: "Mapa do salão", description: "Mesas, comandas e estados do atendimento visíveis em uma única operação." }, { title: "Fila da cozinha", description: "Pedidos organizados por entrada, preparo e conclusão para leitura rápida." }] },
  poseidon: { label: "Sistema para vendas", benefit: "Mantenha cada oportunidade com responsável, contexto e próximo passo.", featureDescriptions: ["Acompanhe negociações sem depender de anotações soltas.", "Agende a próxima ação diretamente na oportunidade correta.", "Preserve ligações, reuniões, decisões e observações em uma linha do tempo.", "Registre ganhos e perdas para entender o andamento da carteira."], screens: [{ title: "Carteira comercial", description: "Oportunidades com etapa, valor, responsável e próxima ação em destaque." }, { title: "Histórico da negociação", description: "Contatos, arquivos e decisões reunidos para manter o contexto comercial." }] },
  ares: { label: "Sistema de orçamentos", benefit: "Crie propostas profissionais, acompanhe versões e registre a decisão do cliente.", featureDescriptions: ["Monte documentos com itens, quantidades, valores e condições.", "Crie novas versões sem apagar a proposta anterior.", "Apresente uma prévia organizada antes de imprimir ou compartilhar.", "Acompanhe validade e situação de cada proposta."], screens: [{ title: "Editor da proposta", description: "Conteúdo e valores editados enquanto a prévia do documento é atualizada." }, { title: "Documento para o cliente", description: "Uma apresentação limpa do orçamento, pronta para impressão ou compartilhamento manual." }] },
  pandora: { label: "Sistema de NPS e pesquisas", benefit: "Transforme notas e comentários dos clientes em prioridades visíveis.", featureDescriptions: ["Crie e edite pesquisas para cada momento da experiência.", "Compartilhe links, mensagens e cartazes para impressão.", "Calcule NPS e acompanhe respostas que ainda precisam de tratamento.", "Organize comentários por tema para orientar melhorias."], screens: [{ title: "Visão das pesquisas", description: "NPS, prioridades e respostas recentes em uma leitura objetiva." }, { title: "Comentários dos clientes", description: "Feedbacks individuais organizados para identificar elogios, problemas e sugestões." }] },
  hercules: { label: "Sistema de inspeções", benefit: "Execute checklists, registre evidências e acompanhe correções.", featureDescriptions: ["Monte modelos completos com itens e orientações próprias.", "Marque conformidade, não conformidade ou item não aplicável.", "Anexe fotos e observações diretamente no ponto inspecionado.", "Acompanhe ação corretiva, responsável e validação do desvio."], screens: [{ title: "Execução da inspeção", description: "Itens grandes, progresso visível e respostas rápidas para uso em campo." }, { title: "Resumo das não conformidades", description: "Desvios, evidências e responsáveis concentrados para acompanhamento." }] },
  alexandria: { label: "Sistema para bibliotecas", benefit: "Organize obras, exemplares, empréstimos e reservas.", featureDescriptions: ["Cadastre a obra uma vez e controle separadamente cada exemplar físico.", "Encontre títulos por autor, categoria, ISBN ou localização.", "Registre empréstimos, reservas e devoluções.", "Acompanhe disponibilidade e histórico de circulação."], screens: [{ title: "Catálogo do acervo", description: "Obras, autores, categorias e disponibilidade encontrados com rapidez." }, { title: "Circulação dos exemplares", description: "Empréstimos, reservas e devoluções vinculados ao exemplar correto." }] },
  olympus: { label: "Sistema para imobiliárias", benefit: "Acompanhe imóveis, interessados, visitas e propostas até o encerramento.", featureDescriptions: ["Organize a carteira por finalidade, tipo, situação e responsável.", "Preserve características, arquivos e documentos de cada imóvel.", "Registre visitas e a percepção dos interessados.", "Acompanhe venda ou locação sem perder o histórico da negociação."], screens: [{ title: "Carteira de imóveis", description: "Imóveis organizados por finalidade, situação e corretor responsável." }, { title: "Ficha do imóvel", description: "Características, visitas, propostas e documentos reunidos na mesma página." }] },
  argus: { label: "Sistema de patrimônio", benefit: "Saiba onde está cada bem, quem responde por ele e qual seu estado.", featureDescriptions: ["Identifique bens por número patrimonial, categoria e localização.", "Registre responsáveis, empréstimos e transferências.", "Acompanhe manutenção, conservação e ocorrências.", "Realize conferências e preserve documentos e garantias."], screens: [{ title: "Cadastro patrimonial", description: "Bens identificados por número, localização, responsável e conservação." }, { title: "Movimentações do bem", description: "Transferências, termos, manutenções e histórico em ordem cronológica." }] },
  hermes: { label: "Sistema para eventos", benefit: "Planeje programação, participantes, credenciamento e presença.", featureDescriptions: ["Organize eventos, espaços, horários e responsáveis.", "Controle inscrições, confirmações e capacidade.", "Registre credenciamento e presença rapidamente.", "Acompanhe ocorrências e encerramento do evento."], screens: [{ title: "Painel do evento", description: "Programação, capacidade, participantes e pendências em um só contexto." }, { title: "Credenciamento", description: "Busca e confirmação de presença desenhadas para uso rápido no dia do evento." }] },
  athena: { label: "Sistema de licitações", benefit: "Centralize editais, prazos, documentos e decisões internas.", featureDescriptions: ["Cadastre oportunidades e registre a decisão de participar ou não.", "Estruture objeto, riscos, datas e responsáveis.", "Acompanhe validade dos documentos da empresa.", "Registre etapas, sessão e resultado do processo."], screens: [{ title: "Central de prazos", description: "Sessões, propostas e documentos que exigem atenção organizados por prioridade." }, { title: "Dossiê da licitação", description: "Edital, riscos, responsáveis e resultado reunidos para acompanhamento interno." }] },
  gaia: { label: "Sistema de produção rural", benefit: "Acompanhe safra, talhões, atividades e observações de campo.", featureDescriptions: ["Organize propriedades, áreas, culturas e ciclos produtivos.", "Planeje e registre atividades executadas no campo.", "Adicione observações técnicas e evidências por área.", "Acompanhe áreas, máquinas e pontos de atenção da safra."], screens: [{ title: "Visão da safra", description: "Áreas, culturas e andamento das atividades apresentados de forma simples." }, { title: "Histórico do talhão", description: "Operações, observações e evidências vinculadas à área correta." }] },
  pegasus: { label: "Sistema para pet shops", benefit: "Mantenha cada pet com agenda, cuidados, alertas e histórico próprio.", featureDescriptions: ["Cadastre tutor, contato de emergência, comportamento e restrições.", "Organize banho, tosa e outros atendimentos.", "Separe a situação permanente do pet da etapa de cada serviço.", "Registre vacinas, documentos e cuidados informados pelo tutor."], screens: [{ title: "Agenda e atendimentos", description: "Serviços com pet, tutor e alertas importantes reunidos em uma visão clara." }, { title: "Ficha completa do pet", description: "Cuidados, restrições, vacinas e histórico organizados ao redor do animal." }] },
  titans: { label: "Sistema para construtoras", benefit: "Conecte avanço físico, diário, projetos e pendências da obra.", featureDescriptions: ["Acompanhe etapas, responsáveis e progresso da execução.", "Registre diário de obra, equipe, condições e ocorrências.", "Mantenha projetos, revisões e documentos vigentes identificados.", "Atribua marcos, bloqueios, decisões e evidências aos responsáveis."], screens: [{ title: "Painel da obra", description: "Avanço, etapas, responsáveis e pendências visualizados em poucos segundos." }, { title: "Diário e evidências", description: "Ocorrências, fotos, decisões e documentos registrados por data." }] },
};

const fallback: ProductPresentation = {
  label: "Sistema de gestão",
  benefit: "Organize sua rotina em um fluxo claro e visual.",
  featureDescriptions: ["Centralize informações importantes.", "Acompanhe etapas e responsáveis.", "Preserve histórico e observações.", "Consulte registros com rapidez."],
  screens: [{ title: "Visão principal", description: "Acompanhe os registros mais importantes da rotina." }, { title: "Detalhe do registro", description: "Consulte dados, histórico e próximas ações." }],
};

export function getProductPresentation(slug: string): ProductPresentation {
  return presentations[slug] ?? fallback;
}
