export type ProductPresentation = {
  label: string;
  benefit: string;
  featureDescriptions: string[];
};

const presentations: Record<string, ProductPresentation> = {
  atlas: { label: "Sistema para oficinas", benefit: "Acompanhe cada veículo, atendimento e próxima ação sem perder o histórico.", featureDescriptions: ["Visualize os veículos por etapa e identifique rapidamente o que está parado.", "Registre o relato do cliente, a avaliação da oficina e a conclusão técnica.", "Mantenha fotos e observações vinculadas ao atendimento correto.", "Acompanhe aprovação, execução e entrega sem misturar informações."] },
  zeus: { label: "Gestão de frotas", benefit: "Organize veículos, motoristas, documentos e manutenções em uma visão direta.", featureDescriptions: ["Consulte situação, quilometragem e responsável por cada veículo.", "Programe manutenções preventivas sem depender de controles dispersos.", "Acompanhe motoristas, habilitações e documentos importantes.", "Registre abastecimentos e ocorrências para preservar o histórico da frota."] },
  artemis: { label: "Sistema para restaurantes", benefit: "Conecte salão, comandas e cozinha em um fluxo simples de atendimento.", featureDescriptions: ["Veja mesas livres, ocupadas, na cozinha ou prontas para servir.", "Adicione itens, quantidades e observações diretamente na comanda.", "Envie pedidos e acompanhe a fila de preparo em tempo real local.", "Controle disponibilidade, categorias e preços do cardápio."] },
  poseidon: { label: "Sistema para vendas", benefit: "Mantenha cada oportunidade com responsável, contexto e próximo passo.", featureDescriptions: ["Acompanhe negociações sem depender de planilhas ou anotações soltas.", "Defina a próxima ação e destaque contatos que precisam de retorno.", "Preserve ligações, reuniões, decisões e observações em uma linha do tempo.", "Registre ganhos e perdas para entender o andamento da carteira."] },
  ares: { label: "Sistema de orçamentos", benefit: "Crie propostas profissionais, acompanhe versões e registre a decisão do cliente.", featureDescriptions: ["Monte documentos com itens, quantidades, valores e condições.", "Reaproveite estruturas prontas para criar novas propostas com agilidade.", "Apresente uma prévia organizada antes de imprimir ou compartilhar.", "Acompanhe envio, visualização, aprovação e reprovação."] },
  pandora: { label: "Sistema de NPS e pesquisas", benefit: "Transforme notas e comentários dos clientes em prioridades visíveis.", featureDescriptions: ["Crie pesquisas adequadas para cada momento da experiência.", "Compartilhe links e QR Codes de forma simples.", "Acompanhe notas, distribuição e evolução das respostas.", "Organize comentários por tema para orientar melhorias."] },
  hercules: { label: "Sistema de inspeções", benefit: "Execute checklists, registre evidências e acompanhe correções.", featureDescriptions: ["Use modelos organizados por etapas, áreas ou tipos de inspeção.", "Marque conformidade, não conformidade ou item não aplicável.", "Anexe fotos e observações diretamente no ponto inspecionado.", "Acompanhe desvios, responsáveis e validação da correção."] },
  alexandria: { label: "Sistema para bibliotecas", benefit: "Organize obras, exemplares, leitores, empréstimos e reservas.", featureDescriptions: ["Cadastre a obra uma vez e controle separadamente cada exemplar físico.", "Encontre títulos por autor, categoria, ISBN ou localização.", "Registre empréstimos, renovações, reservas e devoluções.", "Acompanhe disponibilidade, restrições e histórico de circulação."] },
  olympus: { label: "Sistema para imobiliárias", benefit: "Acompanhe imóveis, interessados, visitas e propostas até o encerramento.", featureDescriptions: ["Organize a carteira por finalidade, tipo, situação e responsável.", "Preserve fotos, características e documentos de cada imóvel.", "Agende visitas e registre a percepção dos interessados.", "Acompanhe propostas e decisões sem perder o histórico da negociação."] },
  argus: { label: "Sistema de patrimônio", benefit: "Saiba onde está cada bem, quem responde por ele e qual seu estado.", featureDescriptions: ["Identifique bens por número patrimonial, categoria e localização.", "Registre responsáveis, empréstimos e transferências.", "Acompanhe manutenção, conservação e ocorrências.", "Realize conferências e preserve documentos e garantias."] },
  hermes: { label: "Sistema para eventos", benefit: "Planeje programação, participantes, credenciamento e presença.", featureDescriptions: ["Organize eventos, espaços, horários e responsáveis.", "Controle inscrições, confirmações e capacidade.", "Realize credenciamento e registre presença rapidamente.", "Acompanhe ocorrências e encerramento do evento."] },
  athena: { label: "Sistema de licitações", benefit: "Centralize editais, prazos, documentos e decisões internas.", featureDescriptions: ["Cadastre oportunidades e decida quais merecem análise.", "Estruture exigências, objeto, datas e responsáveis.", "Acompanhe validade dos documentos da empresa.", "Registre sessão, habilitação, resultado e possíveis recursos."] },
  gaia: { label: "Sistema de produção rural", benefit: "Acompanhe safra, talhões, atividades e resultados de campo.", featureDescriptions: ["Organize propriedades, áreas, culturas e ciclos produtivos.", "Planeje e registre atividades executadas no campo.", "Adicione observações técnicas e evidências por área.", "Compare produção e ocorrências ao longo da safra."] },
  pegasus: { label: "Sistema para pet shops", benefit: "Mantenha cada pet com agenda, cuidados, alertas e histórico próprio.", featureDescriptions: ["Cadastre tutor, pet, comportamento, preferências e restrições.", "Organize banho, tosa, consultas e outros serviços.", "Acompanhe hospedagem, creche, entrada e retirada.", "Registre vacinas, observações e comunicação com o tutor."] },
  titans: { label: "Sistema para construtoras", benefit: "Conecte avanço físico, diário, projetos e pendências da obra.", featureDescriptions: ["Acompanhe etapas e progresso sem misturar com controle financeiro.", "Registre diário de obra, equipe, condições e ocorrências.", "Mantenha projetos, revisões e documentos vigentes identificados.", "Atribua pendências, decisões e evidências aos responsáveis."] },
};

export function getProductPresentation(slug: string): ProductPresentation {
  return presentations[slug] ?? { label: "Sistema de gestão", benefit: "Organize sua rotina em um fluxo claro e visual.", featureDescriptions: ["Centralize informações importantes.", "Acompanhe etapas e responsáveis.", "Preserve histórico e observações.", "Consulte registros com rapidez."] };
}
