from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise RuntimeError(f"Trecho não encontrado em {label}")
    return text.replace(old, new, 1)


# PANDORA
path = Path("components/workspaces/phase-four/PandoraApp.tsx")
text = path.read_text(encoding="utf-8")
if 'const [scope, setScope] = useState<"Em acompanhamento" | "Finalizadas">("Em acompanhamento");' not in text:
    text = replace_once(text, '  const [statusFilter, setStatusFilter] = useState<FeedbackStatus | "Todas">("Todas");\n', '  const [statusFilter, setStatusFilter] = useState<FeedbackStatus | "Todas">("Todas");\n  const [scope, setScope] = useState<"Em acompanhamento" | "Finalizadas">("Em acompanhamento");\n  const [sortMode, setSortMode] = useState<"Mais recentes" | "Prioridade" | "Menor nota" | "Prazo">("Mais recentes");\n  const [surveyQuery, setSurveyQuery] = useState("");\n  const [surveyStatus, setSurveyStatus] = useState<"Todas" | "Ativas" | "Pausadas">("Todas");\n  const [surveySort, setSurveySort] = useState<"Nome" | "Mais respostas">("Nome");\n  const [themeQuery, setThemeQuery] = useState("");\n  const [themeSort, setThemeSort] = useState<"Mais citados" | "Mais pendências" | "Menor nota">("Mais citados");\n', "Pandora estados")
    old_filtered = '''  const filtered = useMemo(() => {
    const value = query.trim().toLowerCase();
    return feedbacks.filter((feedback) => {
      const scoreGroup = feedback.score <= 6 ? "Detratores" : feedback.score <= 8 ? "Neutros" : "Promotores";
      return (group === "Todas" || group === scoreGroup) && (statusFilter === "Todas" || feedback.status === statusFilter) && (!value || `${feedback.customer} ${feedback.comment} ${feedback.theme} ${feedback.channel} ${feedback.owner}`.toLowerCase().includes(value));
    });
  }, [feedbacks, group, query, statusFilter]);
'''
    new_filtered = '''  const filtered = useMemo(() => {
    const value = query.trim().toLowerCase();
    const scoped = feedbacks.filter((feedback) => {
      const scoreGroup = feedback.score <= 6 ? "Detratores" : feedback.score <= 8 ? "Neutros" : "Promotores";
      return (scope === "Finalizadas" ? feedback.status === "Tratado" : feedback.status !== "Tratado") && (group === "Todas" || group === scoreGroup) && (statusFilter === "Todas" || feedback.status === statusFilter) && (!value || `${feedback.customer} ${feedback.comment} ${feedback.theme} ${feedback.channel} ${feedback.owner}`.toLowerCase().includes(value));
    });
    return [...scoped].sort((a, b) => sortMode === "Prioridade" ? Number(b.priority) - Number(a.priority) : sortMode === "Menor nota" ? a.score - b.score : sortMode === "Prazo" ? (a.dueDate || "9999").localeCompare(b.dueDate || "9999") : feedbacks.indexOf(a) - feedbacks.indexOf(b));
  }, [feedbacks, group, query, scope, sortMode, statusFilter]);
'''
    text = replace_once(text, old_filtered, new_filtered, "Pandora respostas")
    old_theme = '''  const themeStats = useMemo(() => {
    const counts = new Map<string, { count: number; score: number; pending: number }>();
    feedbacks.forEach((feedback) => { const current = counts.get(feedback.theme) ?? { count: 0, score: 0, pending: 0 }; counts.set(feedback.theme, { count: current.count + 1, score: current.score + feedback.score, pending: current.pending + (feedback.status === "Tratado" ? 0 : 1) }); });
    return Array.from(counts.entries()).map(([name, data]) => ({ name, count: data.count, pending: data.pending, average: data.score / data.count })).sort((a, b) => b.count - a.count);
  }, [feedbacks]);
'''
    new_theme = '''  const themeStats = useMemo(() => {
    const counts = new Map<string, { count: number; score: number; pending: number }>();
    feedbacks.forEach((feedback) => { const current = counts.get(feedback.theme) ?? { count: 0, score: 0, pending: 0 }; counts.set(feedback.theme, { count: current.count + 1, score: current.score + feedback.score, pending: current.pending + (feedback.status === "Tratado" ? 0 : 1) }); });
    return Array.from(counts.entries()).map(([name, data]) => ({ name, count: data.count, pending: data.pending, average: data.score / data.count }));
  }, [feedbacks]);
  const visibleSurveys = useMemo(() => surveys.filter((survey) => (surveyStatus === "Todas" || (surveyStatus === "Ativas" ? survey.active : !survey.active)) && `${survey.name} ${survey.question}`.toLowerCase().includes(surveyQuery.trim().toLowerCase())).sort((a, b) => surveySort === "Mais respostas" ? surveyResponseCount(b) - surveyResponseCount(a) : a.name.localeCompare(b.name, "pt-BR")), [feedbacks, surveyQuery, surveySort, surveyStatus, surveys]);
  const visibleThemes = useMemo(() => themeStats.filter((theme) => theme.name.toLowerCase().includes(themeQuery.trim().toLowerCase())).sort((a, b) => themeSort === "Mais pendências" ? b.pending - a.pending : themeSort === "Menor nota" ? a.average - b.average : b.count - a.count), [themeQuery, themeSort, themeStats]);
'''
    text = replace_once(text, old_theme, new_theme, "Pandora pesquisas e temas")
    old_toolbar = '<div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cliente, tema ou responsável" /></label><select className={styles.compactSelect} value={statusFilter} onChange={(event) => { setStatusFilter(event.target.value as FeedbackStatus | "Todas"); setSelectedId(""); }}><option>Todas</option><option>Novo</option><option>Em análise</option><option>Aguardando retorno</option><option>Tratado</option></select></div><div className={styles.feedbackFilter}>'
    new_toolbar = '<div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cliente, tema ou responsável" /></label><select className={styles.compactSelect} value={statusFilter} onChange={(event) => { setStatusFilter(event.target.value as FeedbackStatus | "Todas"); setSelectedId(""); }}><option>Todas</option><option>Novo</option><option>Em análise</option><option>Aguardando retorno</option><option>Tratado</option></select><select className={styles.compactSelect} value={sortMode} onChange={(event) => setSortMode(event.target.value as typeof sortMode)}><option>Mais recentes</option><option>Prioridade</option><option>Menor nota</option><option>Prazo</option></select></div><div className={styles.segmented}><button className={scope === "Em acompanhamento" ? styles.segmentActive : ""} onClick={() => { setScope("Em acompanhamento"); setStatusFilter("Todas"); setSelectedId(""); }}>Em acompanhamento <span>{feedbacks.filter((item) => item.status !== "Tratado").length}</span></button><button className={scope === "Finalizadas" ? styles.segmentActive : ""} onClick={() => { setScope("Finalizadas"); setStatusFilter("Todas"); setSelectedId(""); }}>Finalizadas <span>{feedbacks.filter((item) => item.status === "Tratado").length}</span></button></div><div className={styles.feedbackFilter}>'
    text = replace_once(text, old_toolbar, new_toolbar, "Pandora barra de respostas")
    old_surveys = '    {active === "Pesquisas" ? <section className={styles.pageSheet}><div className={styles.surveyRows}>{surveys.map((survey) =>'
    new_surveys = '    {active === "Pesquisas" ? <section className={styles.pageSheet}><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={surveyQuery} onChange={(event) => setSurveyQuery(event.target.value)} placeholder="Buscar pesquisa" /></label><select className={styles.compactSelect} value={surveyStatus} onChange={(event) => setSurveyStatus(event.target.value as typeof surveyStatus)}><option>Todas</option><option>Ativas</option><option>Pausadas</option></select><select className={styles.compactSelect} value={surveySort} onChange={(event) => setSurveySort(event.target.value as typeof surveySort)}><option>Nome</option><option>Mais respostas</option></select></div><div className={styles.surveyRows}>{visibleSurveys.map((survey) =>'
    text = replace_once(text, old_surveys, new_surveys, "Pandora pesquisas")
    old_share = '    {active === "Compartilhar" ? <section className={styles.pageSheet}><div className={styles.distributionGrid}>{surveys.filter((survey) => survey.active).map((survey) =>'
    new_share = '    {active === "Compartilhar" ? <section className={styles.pageSheet}><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={surveyQuery} onChange={(event) => setSurveyQuery(event.target.value)} placeholder="Buscar pesquisa ativa" /></label><select className={styles.compactSelect} value={surveySort} onChange={(event) => setSurveySort(event.target.value as typeof surveySort)}><option>Nome</option><option>Mais respostas</option></select></div><div className={styles.distributionGrid}>{visibleSurveys.filter((survey) => survey.active).map((survey) =>'
    text = replace_once(text, old_share, new_share, "Pandora compartilhar")
    old_themes = '    {active === "Temas" ? <section className={styles.pageSheet}><div className={styles.themeRows}>{themeStats.map((theme) =>'
    new_themes = '    {active === "Temas" ? <section className={styles.pageSheet}><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={themeQuery} onChange={(event) => setThemeQuery(event.target.value)} placeholder="Buscar tema" /></label><select className={styles.compactSelect} value={themeSort} onChange={(event) => setThemeSort(event.target.value as typeof themeSort)}><option>Mais citados</option><option>Mais pendências</option><option>Menor nota</option></select></div><div className={styles.themeRows}>{visibleThemes.map((theme) =>'
    text = replace_once(text, old_themes, new_themes, "Pandora temas")
    path.write_text(text, encoding="utf-8")


# POSEIDON
path = Path("components/workspaces/phase-four/PoseidonApp.tsx")
text = path.read_text(encoding="utf-8")
if 'const [opportunitySort, setOpportunitySort]' not in text:
    text = replace_once(text, '  const [activityMode, setActivityMode] = useState<"Pendentes" | "Concluídas">("Pendentes");\n', '  const [activityMode, setActivityMode] = useState<"Pendentes" | "Concluídas">("Pendentes");\n  const [opportunitySort, setOpportunitySort] = useState<"Mais recentes" | "Maior valor" | "Empresa" | "Etapa">("Mais recentes");\n  const [activityQuery, setActivityQuery] = useState("");\n  const [activityType, setActivityType] = useState("Todos");\n  const [activitySort, setActivitySort] = useState<"Mais próximas" | "Mais recentes" | "Empresa">("Mais próximas");\n  const [contactQuery, setContactQuery] = useState("");\n  const [contactSort, setContactSort] = useState<"Nome" | "Empresa" | "Mais oportunidades">("Nome");\n  const [closedQuery, setClosedQuery] = useState("");\n  const [closedStage, setClosedStage] = useState<"Todas" | "Ganha" | "Perdida">("Todas");\n  const [closedSort, setClosedSort] = useState<"Mais recentes" | "Maior valor" | "Empresa">("Mais recentes");\n', "Poseidon estados")
    old_filtered = '''  const filtered = useMemo(() => {
    const value = query.trim().toLowerCase();
    return opportunities.filter((item) => !["Ganha", "Perdida"].includes(item.stage) && (stageFilter === "Todas" || item.stage === stageFilter) && (!value || `${item.company} ${item.contact} ${item.owner} ${item.next} ${item.source}`.toLowerCase().includes(value)));
  }, [opportunities, query, stageFilter]);
  const displayedActivities = useMemo(() => activities.filter((item) => activityMode === "Pendentes" ? !item.done : item.done).sort((a, b) => `${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)), [activities, activityMode]);
'''
    new_filtered = '''  const filtered = useMemo(() => {
    const value = query.trim().toLowerCase();
    const scoped = opportunities.filter((item) => !["Ganha", "Perdida"].includes(item.stage) && (stageFilter === "Todas" || item.stage === stageFilter) && (!value || `${item.company} ${item.contact} ${item.owner} ${item.next} ${item.source}`.toLowerCase().includes(value)));
    return [...scoped].sort((a, b) => opportunitySort === "Maior valor" ? b.value - a.value : opportunitySort === "Empresa" ? a.company.localeCompare(b.company, "pt-BR") : opportunitySort === "Etapa" ? openStages.indexOf(a.stage as OpenStage) - openStages.indexOf(b.stage as OpenStage) : opportunities.indexOf(a) - opportunities.indexOf(b));
  }, [opportunities, opportunitySort, query, stageFilter]);
  const activityTypes = useMemo(() => ["Todos", ...Array.from(new Set(activities.map((item) => item.type))).sort()], [activities]);
  const displayedActivities = useMemo(() => { const value = activityQuery.trim().toLowerCase(); const scoped = activities.filter((item) => (activityMode === "Pendentes" ? !item.done : item.done) && (activityType === "Todos" || item.type === activityType) && (!value || `${item.company} ${item.person} ${item.type} ${item.result ?? ""}`.toLowerCase().includes(value))); return [...scoped].sort((a, b) => activitySort === "Empresa" ? a.company.localeCompare(b.company, "pt-BR") : activitySort === "Mais recentes" ? `${b.date}${b.time}`.localeCompare(`${a.date}${a.time}`) : `${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)); }, [activities, activityMode, activityQuery, activitySort, activityType]);
'''
    text = replace_once(text, old_filtered, new_filtered, "Poseidon oportunidades e atividades")
    old_contacts_end = '''    return Array.from(map.values());
  }, [opportunities]);
'''
    new_contacts_end = '''    return Array.from(map.values());
  }, [opportunities]);
  const visibleContacts = useMemo(() => contacts.filter((item) => `${item.contact} ${item.company} ${item.phone}`.toLowerCase().includes(contactQuery.trim().toLowerCase())).sort((a, b) => contactSort === "Empresa" ? a.company.localeCompare(b.company, "pt-BR") : contactSort === "Mais oportunidades" ? b.count - a.count : a.contact.localeCompare(b.contact, "pt-BR")), [contactQuery, contactSort, contacts]);
  const closedOpportunities = useMemo(() => { const value = closedQuery.trim().toLowerCase(); const scoped = opportunities.filter((item) => ["Ganha", "Perdida"].includes(item.stage) && (closedStage === "Todas" || item.stage === closedStage) && (!value || `${item.company} ${item.contact} ${item.lossReason ?? ""} ${item.closureNote ?? ""}`.toLowerCase().includes(value))); return [...scoped].sort((a, b) => closedSort === "Maior valor" ? b.value - a.value : closedSort === "Empresa" ? a.company.localeCompare(b.company, "pt-BR") : opportunities.indexOf(a) - opportunities.indexOf(b)); }, [closedQuery, closedSort, closedStage, opportunities]);
'''
    text = replace_once(text, old_contacts_end, new_contacts_end, "Poseidon contatos e encerradas")
    old_toolbar = '<div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Empresa, contato, origem ou responsável" /></label><select className={styles.compactSelect} value={stageFilter} onChange={(event) => { setStageFilter(event.target.value as OpenStage | "Todas"); setSelectedId(""); }}><option>Todas</option>{openStages.map((stage) => <option key={stage}>{stage}</option>)}</select></div>'
    new_toolbar = '<div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Empresa, contato, origem ou responsável" /></label><select className={styles.compactSelect} value={stageFilter} onChange={(event) => { setStageFilter(event.target.value as OpenStage | "Todas"); setSelectedId(""); }}><option>Todas</option>{openStages.map((stage) => <option key={stage}>{stage}</option>)}</select><select className={styles.compactSelect} value={opportunitySort} onChange={(event) => setOpportunitySort(event.target.value as typeof opportunitySort)}><option>Mais recentes</option><option>Maior valor</option><option>Empresa</option><option>Etapa</option></select></div>'
    text = replace_once(text, old_toolbar, new_toolbar, "Poseidon barra de oportunidades")
    old_activities = '    {active === "Atividades" ? <section className={styles.pageSheet}><div className={styles.pageHeading}><div><span className={styles.eyebrow}>Agenda comercial</span><h2>Atividades e retornos</h2><p>Concluir uma atividade exige resultado e próxima ação.</p></div></div><div className={styles.segmented}>'
    new_activities = '    {active === "Atividades" ? <section className={styles.pageSheet}><div className={styles.pageHeading}><div><span className={styles.eyebrow}>Agenda comercial</span><h2>Atividades e retornos</h2><p>Concluir uma atividade exige resultado e próxima ação.</p></div></div><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={activityQuery} onChange={(event) => setActivityQuery(event.target.value)} placeholder="Empresa, contato ou resultado" /></label><select className={styles.compactSelect} value={activityType} onChange={(event) => setActivityType(event.target.value)}>{activityTypes.map((type) => <option key={type}>{type}</option>)}</select><select className={styles.compactSelect} value={activitySort} onChange={(event) => setActivitySort(event.target.value as typeof activitySort)}><option>Mais próximas</option><option>Mais recentes</option><option>Empresa</option></select></div><div className={styles.segmented}>'
    text = replace_once(text, old_activities, new_activities, "Poseidon atividades")
    old_contacts = '    {active === "Contatos" ? <section className={styles.pageSheet}><div className={styles.directoryRows}>{contacts.map((item) =>'
    new_contacts = '    {active === "Contatos" ? <section className={styles.pageSheet}><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={contactQuery} onChange={(event) => setContactQuery(event.target.value)} placeholder="Contato, empresa ou telefone" /></label><select className={styles.compactSelect} value={contactSort} onChange={(event) => setContactSort(event.target.value as typeof contactSort)}><option>Nome</option><option>Empresa</option><option>Mais oportunidades</option></select></div><div className={styles.directoryRows}>{visibleContacts.map((item) =>'
    text = replace_once(text, old_contacts, new_contacts, "Poseidon contatos")
    old_closed = '    {active === "Encerradas" ? <section className={styles.pageSheet}><div className={styles.pageHeading}><div><span className={styles.eyebrow}>Decisões registradas</span><h2>Ganhos e perdas</h2><p>Clique para consultar a etapa final e o histórico.</p></div></div><div className={styles.directoryRows}>{opportunities.filter((item) => ["Ganha", "Perdida"].includes(item.stage)).map((item) =>'
    new_closed = '    {active === "Encerradas" ? <section className={styles.pageSheet}><div className={styles.pageHeading}><div><span className={styles.eyebrow}>Decisões registradas</span><h2>Ganhos e perdas</h2><p>Clique para consultar a etapa final e o histórico.</p></div></div><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={closedQuery} onChange={(event) => setClosedQuery(event.target.value)} placeholder="Empresa, contato ou motivo" /></label><select className={styles.compactSelect} value={closedStage} onChange={(event) => setClosedStage(event.target.value as typeof closedStage)}><option>Todas</option><option>Ganha</option><option>Perdida</option></select><select className={styles.compactSelect} value={closedSort} onChange={(event) => setClosedSort(event.target.value as typeof closedSort)}><option>Mais recentes</option><option>Maior valor</option><option>Empresa</option></select></div><div className={styles.directoryRows}>{closedOpportunities.map((item) =>'
    text = replace_once(text, old_closed, new_closed, "Poseidon encerradas")
    path.write_text(text, encoding="utf-8")


# HERCULES
path = Path("components/workspaces/phase-four/HerculesApp.tsx")
text = path.read_text(encoding="utf-8")
if 'const [inspectionScope, setInspectionScope]' not in text:
    text = text.replace('import { useState, type ChangeEvent, type Dispatch, type SetStateAction } from "react";', 'import { useMemo, useState, type ChangeEvent, type Dispatch, type SetStateAction } from "react";')
    text = replace_once(text, '  const [modelDraft, setModelDraft] = useState<{ id: string; name: string; items: ModelItem[] }>({ id: "", name: "", items: [{ id: uid("MDI"), label: "", helper: "" }] });\n', '  const [modelDraft, setModelDraft] = useState<{ id: string; name: string; items: ModelItem[] }>({ id: "", name: "", items: [{ id: uid("MDI"), label: "", helper: "" }] });\n  const [inspectionScope, setInspectionScope] = useState<"Em andamento" | "Histórico">("Em andamento");\n  const [inspectionQuery, setInspectionQuery] = useState("");\n  const [inspectionSort, setInspectionSort] = useState<"Mais recentes" | "Nome" | "Responsável">("Mais recentes");\n  const [scheduledQuery, setScheduledQuery] = useState("");\n  const [scheduledSort, setScheduledSort] = useState<"Data" | "Nome" | "Responsável">("Data");\n  const [deviationScope, setDeviationScope] = useState<"Em acompanhamento" | "Encerrados">("Em acompanhamento");\n  const [deviationStatus, setDeviationStatus] = useState<DeviationStatus | "Todos">("Todos");\n  const [deviationPriority, setDeviationPriority] = useState<Deviation["priority"] | "Todas">("Todas");\n  const [deviationSort, setDeviationSort] = useState<"Prazo" | "Prioridade" | "Responsável">("Prazo");\n  const [modelQuery, setModelQuery] = useState("");\n  const [modelSort, setModelSort] = useState<"Nome" | "Mais itens">("Nome");\n', "Hercules estados")
    marker = '  const isLastItem = Boolean(inspection && currentItem && inspection.items.at(-1)?.id === currentItem.id);\n'
    additions = '''  const isLastItem = Boolean(inspection && currentItem && inspection.items.at(-1)?.id === currentItem.id);
  const visibleInspections = useMemo(() => inspections.filter((item) => item.status !== "Programada" && (inspectionScope === "Histórico" ? item.status === "Concluída" : item.status === "Em execução") && `${item.title} ${item.location} ${item.responsible}`.toLowerCase().includes(inspectionQuery.trim().toLowerCase())).sort((a, b) => inspectionSort === "Nome" ? a.title.localeCompare(b.title, "pt-BR") : inspectionSort === "Responsável" ? a.responsible.localeCompare(b.responsible, "pt-BR") : inspections.indexOf(a) - inspections.indexOf(b)), [inspectionQuery, inspectionScope, inspectionSort, inspections]);
  const visibleScheduled = useMemo(() => inspections.filter((item) => item.status === "Programada" && `${item.title} ${item.location} ${item.responsible}`.toLowerCase().includes(scheduledQuery.trim().toLowerCase())).sort((a, b) => scheduledSort === "Nome" ? a.title.localeCompare(b.title, "pt-BR") : scheduledSort === "Responsável" ? a.responsible.localeCompare(b.responsible, "pt-BR") : a.scheduledAt.localeCompare(b.scheduledAt)), [inspections, scheduledQuery, scheduledSort]);
  const visibleDeviations = useMemo(() => deviations.filter((item) => (deviationScope === "Encerrados" ? item.status === "Encerrado" : item.status !== "Encerrado") && (deviationStatus === "Todos" || item.status === deviationStatus) && (deviationPriority === "Todas" || item.priority === deviationPriority)).sort((a, b) => deviationSort === "Prioridade" ? priorityOrder.indexOf(a.priority) - priorityOrder.indexOf(b.priority) : deviationSort === "Responsável" ? a.responsible.localeCompare(b.responsible, "pt-BR") : a.due.localeCompare(b.due)), [deviationPriority, deviationScope, deviationSort, deviationStatus, deviations]);
  const visibleModels = useMemo(() => models.filter((model) => model.name.toLowerCase().includes(modelQuery.trim().toLowerCase())).sort((a, b) => modelSort === "Mais itens" ? b.items.length - a.items.length : a.name.localeCompare(b.name, "pt-BR")), [modelQuery, modelSort, models]);
'''
    text = replace_once(text, marker, additions, "Hercules listas")
    old_picker = '<section className={styles.pageSheet}><div className={styles.pageHeading}><div><span className={styles.eyebrow}>Escolha consciente</span><h2>Selecione uma inspeção</h2><p>Nenhuma inspeção é aberta automaticamente.</p></div></div><div className={styles.directoryRows}>{inspections.filter((item) => item.status !== "Programada").map((item) =>'
    new_picker = '<section className={styles.pageSheet}><div className={styles.pageHeading}><div><span className={styles.eyebrow}>Escolha consciente</span><h2>Selecione uma inspeção</h2><p>Nenhuma inspeção é aberta automaticamente.</p></div></div><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={inspectionQuery} onChange={(event) => setInspectionQuery(event.target.value)} placeholder="Inspeção, local ou responsável" /></label><select className={styles.compactSelect} value={inspectionSort} onChange={(event) => setInspectionSort(event.target.value as typeof inspectionSort)}><option>Mais recentes</option><option>Nome</option><option>Responsável</option></select></div><div className={styles.segmented}><button className={inspectionScope === "Em andamento" ? styles.segmentActive : ""} onClick={() => setInspectionScope("Em andamento")}>Em andamento <span>{inspections.filter((item) => item.status === "Em execução").length}</span></button><button className={inspectionScope === "Histórico" ? styles.segmentActive : ""} onClick={() => setInspectionScope("Histórico")}>Histórico <span>{inspections.filter((item) => item.status === "Concluída").length}</span></button></div><div className={styles.directoryRows}>{visibleInspections.map((item) =>'
    text = replace_once(text, old_picker, new_picker, "Hercules inspeções")
    old_scheduled = '    {active === "Programadas" ? <section className={styles.pageSheet}><div className={styles.inspectionRows}>{inspections.filter((item) => item.status === "Programada").map((item) =>'
    new_scheduled = '    {active === "Programadas" ? <section className={styles.pageSheet}><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={scheduledQuery} onChange={(event) => setScheduledQuery(event.target.value)} placeholder="Inspeção, local ou responsável" /></label><select className={styles.compactSelect} value={scheduledSort} onChange={(event) => setScheduledSort(event.target.value as typeof scheduledSort)}><option>Data</option><option>Nome</option><option>Responsável</option></select></div><div className={styles.inspectionRows}>{visibleScheduled.map((item) =>'
    text = replace_once(text, old_scheduled, new_scheduled, "Hercules programadas")
    old_deviations = '    {active === "Desvios" ? <section className={styles.pageSheet}><div className={styles.deviationRows}>{deviations.map((item) =>'
    new_deviations = '    {active === "Desvios" ? <section className={styles.pageSheet}><div className={styles.listToolbar}><select className={styles.compactSelect} value={deviationStatus} onChange={(event) => setDeviationStatus(event.target.value as DeviationStatus | "Todos")}><option>Todos</option><option>Aberto</option><option>Em correção</option><option>Validar</option><option>Encerrado</option></select><select className={styles.compactSelect} value={deviationPriority} onChange={(event) => setDeviationPriority(event.target.value as Deviation["priority"] | "Todas")}><option>Todas</option><option>Alta</option><option>Média</option><option>Baixa</option></select><select className={styles.compactSelect} value={deviationSort} onChange={(event) => setDeviationSort(event.target.value as typeof deviationSort)}><option>Prazo</option><option>Prioridade</option><option>Responsável</option></select></div><div className={styles.segmented}><button className={deviationScope === "Em acompanhamento" ? styles.segmentActive : ""} onClick={() => { setDeviationScope("Em acompanhamento"); setDeviationStatus("Todos"); }}>Em acompanhamento <span>{deviations.filter((item) => item.status !== "Encerrado").length}</span></button><button className={deviationScope === "Encerrados" ? styles.segmentActive : ""} onClick={() => { setDeviationScope("Encerrados"); setDeviationStatus("Todos"); }}>Encerrados <span>{deviations.filter((item) => item.status === "Encerrado").length}</span></button></div><div className={styles.deviationRows}>{visibleDeviations.map((item) =>'
    text = replace_once(text, old_deviations, new_deviations, "Hercules desvios")
    old_models = '    {active === "Modelos" ? <section className={styles.pageSheet}><div className={styles.templateGrid}>{models.map((model) =>'
    new_models = '    {active === "Modelos" ? <section className={styles.pageSheet}><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={modelQuery} onChange={(event) => setModelQuery(event.target.value)} placeholder="Buscar modelo" /></label><select className={styles.compactSelect} value={modelSort} onChange={(event) => setModelSort(event.target.value as typeof modelSort)}><option>Nome</option><option>Mais itens</option></select></div><div className={styles.templateGrid}>{visibleModels.map((model) =>'
    text = replace_once(text, old_models, new_models, "Hercules modelos")
    text += '\nconst priorityOrder: Deviation["priority"][] = ["Alta", "Média", "Baixa"];\n'
    path.write_text(text, encoding="utf-8")


# ZEUS
path = Path("components/workspaces/phase-four/ZeusApp.tsx")
text = path.read_text(encoding="utf-8")
if 'const [fleetScope, setFleetScope]' not in text:
    text = replace_once(text, '  const [statusFilter, setStatusFilter] = useState<VehicleStatus | "Todos">("Todos");\n', '  const [statusFilter, setStatusFilter] = useState<VehicleStatus | "Todos">("Todos");\n  const [fleetScope, setFleetScope] = useState<"Operacionais" | "Inativos">("Operacionais");\n  const [fleetSort, setFleetSort] = useState<"Modelo" | "Quilometragem" | "Situação">("Modelo");\n  const [maintenanceMode, setMaintenanceMode] = useState<"Acompanhar" | "Realizadas">("Acompanhar");\n  const [maintenanceQuery, setMaintenanceQuery] = useState("");\n  const [maintenanceSort, setMaintenanceSort] = useState<"Prioridade" | "Veículo" | "Mais recentes">("Prioridade");\n  const [driverScope, setDriverScope] = useState<"Ativos" | "Afastados">("Ativos");\n  const [driverQuery, setDriverQuery] = useState("");\n  const [driverSort, setDriverSort] = useState<"Nome" | "Validade CNH" | "Situação">("Nome");\n  const [documentScope, setDocumentScope] = useState<"Vigentes" | "Vencidos">("Vigentes");\n  const [documentQuery, setDocumentQuery] = useState("");\n  const [documentSort, setDocumentSort] = useState<"Vencimento" | "Veículo" | "Tipo">("Vencimento");\n  const [fuelQuery, setFuelQuery] = useState("");\n  const [fuelSort, setFuelSort] = useState<"Mais recentes" | "Maior valor" | "Veículo">("Mais recentes");\n', "Zeus estados")
    old_computed = '  const filteredVehicles = useMemo(() => { const value = query.trim().toLowerCase(); return vehicles.filter((vehicle) => (statusFilter === "Todos" || vehicle.status === statusFilter) && (!value || `${vehicle.model} ${vehicle.plate} ${vehicle.id} ${vehicle.location}`.toLowerCase().includes(value))); }, [query, statusFilter, vehicles]);\n  const attentionVehicles = useMemo(() => vehicles.filter(needsAttention), [vehicles]);\n  const allDocuments = useMemo(() => vehicles.flatMap((vehicle) => vehicle.documents.map((document) => ({ vehicle, document }))).sort((a, b) => a.document.expiry.localeCompare(b.document.expiry)), [vehicles]);\n  const allFuel = useMemo(() => vehicles.flatMap((vehicle) => vehicle.fuel.map((record) => ({ vehicle, record }))).sort((a, b) => b.record.date.localeCompare(a.record.date)), [vehicles]);\n'
    new_computed = '''  const filteredVehicles = useMemo(() => { const value = query.trim().toLowerCase(); const scoped = vehicles.filter((vehicle) => (fleetScope === "Inativos" ? vehicle.status === "Inativo" : vehicle.status !== "Inativo") && (statusFilter === "Todos" || vehicle.status === statusFilter) && (!value || `${vehicle.model} ${vehicle.plate} ${vehicle.id} ${vehicle.location}`.toLowerCase().includes(value))); return [...scoped].sort((a, b) => fleetSort === "Quilometragem" ? b.odometer - a.odometer : fleetSort === "Situação" ? vehicleStatusOrder.indexOf(a.status) - vehicleStatusOrder.indexOf(b.status) : a.model.localeCompare(b.model, "pt-BR")); }, [fleetScope, fleetSort, query, statusFilter, vehicles]);
  const attentionVehicles = useMemo(() => vehicles.filter(needsAttention), [vehicles]);
  const maintenanceHistory = useMemo(() => vehicles.flatMap((vehicle) => vehicle.maintenance.map((record) => ({ vehicle, record }))), [vehicles]);
  const visibleMaintenance = useMemo(() => maintenanceMode === "Acompanhar" ? [...attentionVehicles].filter((vehicle) => `${vehicle.model} ${vehicle.plate} ${maintenanceAlert(vehicle)}`.toLowerCase().includes(maintenanceQuery.trim().toLowerCase())).sort((a, b) => maintenanceSort === "Veículo" ? a.model.localeCompare(b.model, "pt-BR") : maintenanceSort === "Mais recentes" ? vehicles.indexOf(a) - vehicles.indexOf(b) : Number(needsAttention(b)) - Number(needsAttention(a))) : [...maintenanceHistory].filter(({ vehicle, record }) => `${vehicle.model} ${vehicle.plate} ${record.type} ${record.note}`.toLowerCase().includes(maintenanceQuery.trim().toLowerCase())).sort((a, b) => maintenanceSort === "Veículo" ? a.vehicle.model.localeCompare(b.vehicle.model, "pt-BR") : maintenanceSort === "Mais recentes" ? b.record.date.localeCompare(a.record.date) : b.record.cost - a.record.cost), [attentionVehicles, maintenanceHistory, maintenanceMode, maintenanceQuery, maintenanceSort, vehicles]);
  const visibleDrivers = useMemo(() => drivers.filter((driver) => (driverScope === "Afastados" ? driver.status === "Afastado" : driver.status !== "Afastado") && `${driver.name} ${driver.phone} ${driver.license}`.toLowerCase().includes(driverQuery.trim().toLowerCase())).sort((a, b) => driverSort === "Validade CNH" ? a.licenseExpiry.localeCompare(b.licenseExpiry) : driverSort === "Situação" ? a.status.localeCompare(b.status, "pt-BR") : a.name.localeCompare(b.name, "pt-BR")), [driverQuery, driverScope, driverSort, drivers]);
  const allDocuments = useMemo(() => vehicles.flatMap((vehicle) => vehicle.documents.map((document) => ({ vehicle, document }))), [vehicles]);
  const visibleDocuments = useMemo(() => allDocuments.filter(({ vehicle, document }) => (documentScope === "Vencidos" ? isPast(document.expiry) : !isPast(document.expiry)) && `${vehicle.model} ${vehicle.plate} ${document.type} ${document.note}`.toLowerCase().includes(documentQuery.trim().toLowerCase())).sort((a, b) => documentSort === "Veículo" ? a.vehicle.model.localeCompare(b.vehicle.model, "pt-BR") : documentSort === "Tipo" ? a.document.type.localeCompare(b.document.type, "pt-BR") : a.document.expiry.localeCompare(b.document.expiry)), [allDocuments, documentQuery, documentScope, documentSort]);
  const allFuel = useMemo(() => vehicles.flatMap((vehicle) => vehicle.fuel.map((record) => ({ vehicle, record }))), [vehicles]);
  const visibleFuel = useMemo(() => allFuel.filter(({ vehicle, record }) => `${vehicle.model} ${vehicle.plate} ${record.station}`.toLowerCase().includes(fuelQuery.trim().toLowerCase())).sort((a, b) => fuelSort === "Maior valor" ? b.record.cost - a.record.cost : fuelSort === "Veículo" ? a.vehicle.model.localeCompare(b.vehicle.model, "pt-BR") : b.record.date.localeCompare(a.record.date)), [allFuel, fuelQuery, fuelSort]);
'''
    text = replace_once(text, old_computed, new_computed, "Zeus listas")
    old_fleet_toolbar = '<div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Placa, modelo ou local" /></label><select className={styles.compactSelect} value={statusFilter} onChange={(event) => { setStatusFilter(event.target.value as VehicleStatus | "Todos"); setSelectedId(""); }}><option>Todos</option><option>Disponível</option><option>Em uso</option><option>Manutenção</option><option>Inativo</option></select></div>'
    new_fleet_toolbar = '<div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Placa, modelo ou local" /></label><select className={styles.compactSelect} value={statusFilter} onChange={(event) => { setStatusFilter(event.target.value as VehicleStatus | "Todos"); setSelectedId(""); }}><option>Todos</option><option>Disponível</option><option>Em uso</option><option>Manutenção</option><option>Inativo</option></select><select className={styles.compactSelect} value={fleetSort} onChange={(event) => setFleetSort(event.target.value as typeof fleetSort)}><option>Modelo</option><option>Quilometragem</option><option>Situação</option></select></div><div className={styles.segmented}><button className={fleetScope === "Operacionais" ? styles.segmentActive : ""} onClick={() => { setFleetScope("Operacionais"); setStatusFilter("Todos"); setSelectedId(""); }}>Operacionais <span>{vehicles.filter((vehicle) => vehicle.status !== "Inativo").length}</span></button><button className={fleetScope === "Inativos" ? styles.segmentActive : ""} onClick={() => { setFleetScope("Inativos"); setStatusFilter("Todos"); setSelectedId(""); }}>Histórico / inativos <span>{vehicles.filter((vehicle) => vehicle.status === "Inativo").length}</span></button></div>'
    text = replace_once(text, old_fleet_toolbar, new_fleet_toolbar, "Zeus frota")
    old_maintenance = '    {active === "Manutenções" ? <section className={styles.pageSheet}><div className={zeus.simpleRows}>{attentionVehicles.map((vehicle) => <button key={vehicle.id} onClick={() => openVehicle(vehicle.id)}><div><strong>{vehicle.model} · {vehicle.plate}</strong><p>{maintenanceAlert(vehicle)}</p></div><StatusPill status="Atenção" /><Icon name="chevron" /></button>)}</div></section> : null}\n'
    new_maintenance = '    {active === "Manutenções" ? <section className={styles.pageSheet}><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={maintenanceQuery} onChange={(event) => setMaintenanceQuery(event.target.value)} placeholder="Veículo, placa ou serviço" /></label><select className={styles.compactSelect} value={maintenanceSort} onChange={(event) => setMaintenanceSort(event.target.value as typeof maintenanceSort)}><option>Prioridade</option><option>Veículo</option><option>Mais recentes</option></select></div><div className={styles.segmented}><button className={maintenanceMode === "Acompanhar" ? styles.segmentActive : ""} onClick={() => setMaintenanceMode("Acompanhar")}>Acompanhar <span>{attentionVehicles.length}</span></button><button className={maintenanceMode === "Realizadas" ? styles.segmentActive : ""} onClick={() => setMaintenanceMode("Realizadas")}>Realizadas <span>{maintenanceHistory.length}</span></button></div><div className={zeus.simpleRows}>{maintenanceMode === "Acompanhar" ? (visibleMaintenance as Vehicle[]).map((vehicle) => <button key={vehicle.id} onClick={() => openVehicle(vehicle.id)}><div><strong>{vehicle.model} · {vehicle.plate}</strong><p>{maintenanceAlert(vehicle)}</p></div><StatusPill status="Atenção" /><Icon name="chevron" /></button>) : (visibleMaintenance as Array<{ vehicle: Vehicle; record: MaintenanceRecord }>).map(({ vehicle, record }) => <button key={record.id} onClick={() => openVehicle(vehicle.id)}><div><strong>{record.type} · {vehicle.plate}</strong><p>{formatDate(record.date)} · {record.note || "Sem observação"}</p></div><span>{currency(record.cost)}</span><Icon name="chevron" /></button>)}</div></section> : null}\n'
    text = replace_once(text, old_maintenance, new_maintenance, "Zeus manutenções")
    old_drivers = '    {active === "Motoristas" ? <section className={styles.pageSheet}><div className={zeus.simpleRows}>{drivers.map((driver) =>'
    new_drivers = '    {active === "Motoristas" ? <section className={styles.pageSheet}><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={driverQuery} onChange={(event) => setDriverQuery(event.target.value)} placeholder="Motorista, telefone ou CNH" /></label><select className={styles.compactSelect} value={driverSort} onChange={(event) => setDriverSort(event.target.value as typeof driverSort)}><option>Nome</option><option>Validade CNH</option><option>Situação</option></select></div><div className={styles.segmented}><button className={driverScope === "Ativos" ? styles.segmentActive : ""} onClick={() => setDriverScope("Ativos")}>Ativos <span>{drivers.filter((driver) => driver.status !== "Afastado").length}</span></button><button className={driverScope === "Afastados" ? styles.segmentActive : ""} onClick={() => setDriverScope("Afastados")}>Afastados <span>{drivers.filter((driver) => driver.status === "Afastado").length}</span></button></div><div className={zeus.simpleRows}>{visibleDrivers.map((driver) =>'
    text = replace_once(text, old_drivers, new_drivers, "Zeus motoristas")
    old_docs = '    {active === "Documentos" ? <section className={styles.pageSheet}><div className={zeus.simpleRows}>{allDocuments.map(({ vehicle, document }) =>'
    new_docs = '    {active === "Documentos" ? <section className={styles.pageSheet}><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={documentQuery} onChange={(event) => setDocumentQuery(event.target.value)} placeholder="Veículo, placa ou documento" /></label><select className={styles.compactSelect} value={documentSort} onChange={(event) => setDocumentSort(event.target.value as typeof documentSort)}><option>Vencimento</option><option>Veículo</option><option>Tipo</option></select></div><div className={styles.segmented}><button className={documentScope === "Vigentes" ? styles.segmentActive : ""} onClick={() => setDocumentScope("Vigentes")}>Vigentes <span>{allDocuments.filter(({ document }) => !isPast(document.expiry)).length}</span></button><button className={documentScope === "Vencidos" ? styles.segmentActive : ""} onClick={() => setDocumentScope("Vencidos")}>Vencidos <span>{allDocuments.filter(({ document }) => isPast(document.expiry)).length}</span></button></div><div className={zeus.simpleRows}>{visibleDocuments.map(({ vehicle, document }) =>'
    text = replace_once(text, old_docs, new_docs, "Zeus documentos")
    old_fuel = '    {active === "Combustível" ? <section className={styles.pageSheet}><div className={styles.summaryGrid}><div><span>Litros registrados</span><strong>{allFuel.reduce((sum, item) => sum + item.record.liters, 0).toLocaleString("pt-BR")}</strong></div><div><span>Valor informado</span><strong>{currency(allFuel.reduce((sum, item) => sum + item.record.cost, 0))}</strong></div></div><div className={zeus.simpleRows}>{allFuel.map(({ vehicle, record }) =>'
    new_fuel = '    {active === "Combustível" ? <section className={styles.pageSheet}><div className={styles.summaryGrid}><div><span>Litros registrados</span><strong>{allFuel.reduce((sum, item) => sum + item.record.liters, 0).toLocaleString("pt-BR")}</strong></div><div><span>Valor informado</span><strong>{currency(allFuel.reduce((sum, item) => sum + item.record.cost, 0))}</strong></div></div><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={fuelQuery} onChange={(event) => setFuelQuery(event.target.value)} placeholder="Veículo, placa ou posto" /></label><select className={styles.compactSelect} value={fuelSort} onChange={(event) => setFuelSort(event.target.value as typeof fuelSort)}><option>Mais recentes</option><option>Maior valor</option><option>Veículo</option></select></div><div className={zeus.simpleRows}>{visibleFuel.map(({ vehicle, record }) =>'
    text = replace_once(text, old_fuel, new_fuel, "Zeus combustível")
    text += '\nconst vehicleStatusOrder: VehicleStatus[] = ["Disponível", "Em uso", "Manutenção", "Inativo"];\n'
    path.write_text(text, encoding="utf-8")
