from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise RuntimeError(f"Trecho não encontrado em {label}")
    return text.replace(old, new, 1)


# ATLAS
path = Path("components/workspaces/phase-four/AtlasApp.tsx")
text = path.read_text(encoding="utf-8")
if 'const [statusFilter, setStatusFilter] = useState<WorkStatus | "Todos">("Todos");' not in text:
    text = replace_once(text, '  const [listMode, setListMode] = useState<"Em andamento" | "Concluídas">("Em andamento");\n', '  const [listMode, setListMode] = useState<"Em andamento" | "Concluídas">("Em andamento");\n  const [statusFilter, setStatusFilter] = useState<WorkStatus | "Todos">("Todos");\n  const [sortMode, setSortMode] = useState<"Mais recentes" | "Cliente" | "Veículo" | "Etapa">("Mais recentes");\n  const [agendaMode, setAgendaMode] = useState<"Em aberto" | "Realizadas">("Em aberto");\n  const [agendaQuery, setAgendaQuery] = useState("");\n  const [agendaTypeFilter, setAgendaTypeFilter] = useState("Todos");\n  const [agendaSort, setAgendaSort] = useState<"Horário" | "Cliente" | "Tipo">("Horário");\n', "Atlas estados")
    old_filtered = '  const filtered = useMemo(() => { const value = query.trim().toLowerCase(); return orders.filter((order) => (listMode === "Concluídas" ? order.status === "Entregue" : order.status !== "Entregue") && (!value || `${order.id} ${order.vehicle} ${order.plate} ${order.client} ${order.issue}`.toLowerCase().includes(value))); }, [listMode, orders, query]);\n'
    new_filtered = '''  const filtered = useMemo(() => {
    const value = query.trim().toLowerCase();
    const scoped = orders.filter((order) => (listMode === "Concluídas" ? order.status === "Entregue" : order.status !== "Entregue") && (statusFilter === "Todos" || order.status === statusFilter) && (!value || `${order.id} ${order.vehicle} ${order.plate} ${order.client} ${order.issue}`.toLowerCase().includes(value)));
    return [...scoped].sort((a, b) => sortMode === "Cliente" ? a.client.localeCompare(b.client, "pt-BR") : sortMode === "Veículo" ? a.vehicle.localeCompare(b.vehicle, "pt-BR") : sortMode === "Etapa" ? workStatusOrder.indexOf(a.status) - workStatusOrder.indexOf(b.status) : orders.indexOf(a) - orders.indexOf(b));
  }, [listMode, orders, query, sortMode, statusFilter]);
  const appointmentTypes = useMemo(() => ["Todos", ...Array.from(new Set(appointments.map((item) => item.type))).sort()], [appointments]);
  const filteredAppointments = useMemo(() => {
    const value = agendaQuery.trim().toLowerCase();
    const scoped = appointments.filter((item) => (agendaMode === "Realizadas" ? item.done : !item.done) && (agendaTypeFilter === "Todos" || item.type === agendaTypeFilter) && (!value || `${item.client} ${item.vehicle} ${item.type} ${item.time}`.toLowerCase().includes(value)));
    return [...scoped].sort((a, b) => agendaSort === "Cliente" ? a.client.localeCompare(b.client, "pt-BR") : agendaSort === "Tipo" ? a.type.localeCompare(b.type, "pt-BR") : a.time.localeCompare(b.time));
  }, [agendaMode, agendaQuery, agendaSort, agendaTypeFilter, appointments]);
'''
    text = replace_once(text, old_filtered, new_filtered, "Atlas filtros")
    old_toolbar = '<div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Placa, cliente, veículo ou OS" /></label></div><div className={styles.segmented}><button className={listMode === "Em andamento" ? styles.segmentActive : ""} onClick={() => { setListMode("Em andamento"); setSelectedId(""); }}>Em andamento</button><button className={listMode === "Concluídas" ? styles.segmentActive : ""} onClick={() => { setListMode("Concluídas"); setSelectedId(""); }}>Entregues</button></div>'
    new_toolbar = '<div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Placa, cliente, veículo ou OS" /></label><select className={styles.compactSelect} value={statusFilter} onChange={(event) => { setStatusFilter(event.target.value as WorkStatus | "Todos"); setSelectedId(""); }}><option>Todos</option>{workStatusOrder.map((status) => <option key={status}>{status}</option>)}</select><select className={styles.compactSelect} value={sortMode} onChange={(event) => setSortMode(event.target.value as typeof sortMode)}><option>Mais recentes</option><option>Cliente</option><option>Veículo</option><option>Etapa</option></select></div><div className={styles.segmented}><button className={listMode === "Em andamento" ? styles.segmentActive : ""} onClick={() => { setListMode("Em andamento"); setStatusFilter("Todos"); setSelectedId(""); }}>Em andamento <span>{orders.filter((item) => item.status !== "Entregue").length}</span></button><button className={listMode === "Concluídas" ? styles.segmentActive : ""} onClick={() => { setListMode("Concluídas"); setStatusFilter("Todos"); setSelectedId(""); }}>Histórico <span>{orders.filter((item) => item.status === "Entregue").length}</span></button></div>'
    text = replace_once(text, old_toolbar, new_toolbar, "Atlas barra principal")
    old_agenda = '    {active === "Agenda" ? <section className={styles.pageSheet}><div className={styles.scheduleList}>{appointments.map((item) => <div key={item.id} className={`${styles.scheduleRow} ${item.done ? styles.completedRow : ""}`}><strong>{item.time}</strong><div><span>{item.type}</span><h3>{item.client}</h3><p>{item.vehicle}</p></div>{item.done ? <StatusPill status="Concluído" /> : <button onClick={() => { if (window.confirm(`Confirmar ${item.type.toLowerCase()} de ${item.client}?`)) setAppointments((current) => current.map((entry) => entry.id === item.id ? { ...entry, done: true } : entry)); }}>Confirmar</button>}</div>)}</div></section> : null}\n'
    new_agenda = '    {active === "Agenda" ? <section className={styles.pageSheet}><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={agendaQuery} onChange={(event) => setAgendaQuery(event.target.value)} placeholder="Cliente, veículo ou compromisso" /></label><select className={styles.compactSelect} value={agendaTypeFilter} onChange={(event) => setAgendaTypeFilter(event.target.value)}>{appointmentTypes.map((type) => <option key={type}>{type}</option>)}</select><select className={styles.compactSelect} value={agendaSort} onChange={(event) => setAgendaSort(event.target.value as typeof agendaSort)}><option>Horário</option><option>Cliente</option><option>Tipo</option></select></div><div className={styles.segmented}><button className={agendaMode === "Em aberto" ? styles.segmentActive : ""} onClick={() => setAgendaMode("Em aberto")}>Em aberto <span>{appointments.filter((item) => !item.done).length}</span></button><button className={agendaMode === "Realizadas" ? styles.segmentActive : ""} onClick={() => setAgendaMode("Realizadas")}>Realizadas <span>{appointments.filter((item) => item.done).length}</span></button></div><div className={styles.scheduleList}>{filteredAppointments.map((item) => <div key={item.id} className={`${styles.scheduleRow} ${item.done ? styles.completedRow : ""}`}><strong>{item.time}</strong><div><span>{item.type}</span><h3>{item.client}</h3><p>{item.vehicle}</p></div>{item.done ? <StatusPill status="Concluído" /> : <button onClick={() => { if (window.confirm(`Confirmar ${item.type.toLowerCase()} de ${item.client}?`)) setAppointments((current) => current.map((entry) => entry.id === item.id ? { ...entry, done: true } : entry)); }}>Confirmar</button>}</div>)}{!filteredAppointments.length ? <EmptyState icon={agendaMode === "Realizadas" ? "history" : "calendar"} title={agendaMode === "Realizadas" ? "Nenhuma atividade realizada" : "Nenhum compromisso em aberto"} description="Altere a busca, o filtro ou a classificação." /> : null}</div></section> : null}\n'
    text = replace_once(text, old_agenda, new_agenda, "Atlas agenda")
    old_directory = 'function Directory({ rows, onSelect }: { rows: Array<{ id: string; title: string; subtitle: string }>; onSelect: (id: string) => void }) { return <section className={styles.pageSheet}><div className={styles.directoryRows}>{rows.map((row) => <button key={`${row.id}-${row.title}`} onClick={() => onSelect(row.id)}><span className={styles.companyAvatar}>{row.title.slice(0, 2).toUpperCase()}</span><div><strong>{row.title}</strong><small>{row.subtitle}</small></div><Icon name="chevron" /></button>)}</div></section>; }'
    new_directory = 'function Directory({ rows, onSelect }: { rows: Array<{ id: string; title: string; subtitle: string }>; onSelect: (id: string) => void }) { const [query, setQuery] = useState(""); const [sort, setSort] = useState<"Nome" | "Mais recentes">("Nome"); const visible = [...rows.filter((row) => `${row.title} ${row.subtitle}`.toLowerCase().includes(query.trim().toLowerCase()))].sort((a, b) => sort === "Nome" ? a.title.localeCompare(b.title, "pt-BR") : rows.indexOf(a) - rows.indexOf(b)); return <section className={styles.pageSheet}><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar registro" /></label><select className={styles.compactSelect} value={sort} onChange={(event) => setSort(event.target.value as typeof sort)}><option>Nome</option><option>Mais recentes</option></select></div><div className={styles.directoryRows}>{visible.map((row) => <button key={`${row.id}-${row.title}`} onClick={() => onSelect(row.id)}><span className={styles.companyAvatar}>{row.title.slice(0, 2).toUpperCase()}</span><div><strong>{row.title}</strong><small>{row.subtitle}</small></div><Icon name="chevron" /></button>)}{!visible.length ? <EmptyState icon="search" title="Nenhum registro encontrado" description="Altere a busca ou a classificação." /> : null}</div></section>; }'
    text = replace_once(text, old_directory, new_directory, "Atlas diretórios")
    text += '\nconst workStatusOrder: WorkStatus[] = ["Avaliação", "Aguardando aprovação", "Aguardando peça", "Em serviço", "Em conferência", "Pronto", "Entregue"];\n'
    path.write_text(text, encoding="utf-8")


# ARES
path = Path("components/workspaces/phase-four/AresApp.tsx")
text = path.read_text(encoding="utf-8")
if 'const [scope, setScope] = useState<"Em andamento" | "Finalizadas">("Em andamento");' not in text:
    text = replace_once(text, 'const statusOptions: QuoteStatus[] = ["Rascunho", "Pronto", "Enviado", "Visualizado", "Alteração solicitada", "Aprovado", "Recusado", "Expirado"];\n', 'const statusOptions: QuoteStatus[] = ["Rascunho", "Pronto", "Enviado", "Visualizado", "Alteração solicitada", "Aprovado", "Recusado", "Expirado"];\nconst finalQuoteStatuses: QuoteStatus[] = ["Alteração solicitada", "Aprovado", "Recusado", "Expirado"];\n', "Ares status finais")
    text = replace_once(text, '  const [statusFilter, setStatusFilter] = useState<QuoteStatus | "Todas">("Todas");\n', '  const [statusFilter, setStatusFilter] = useState<QuoteStatus | "Todas">("Todas");\n  const [scope, setScope] = useState<"Em andamento" | "Finalizadas">("Em andamento");\n  const [sortMode, setSortMode] = useState<"Mais recentes" | "Cliente" | "Valor" | "Validade">("Mais recentes");\n  const [clientQuery, setClientQuery] = useState("");\n  const [clientSort, setClientSort] = useState<"Nome" | "Mais propostas">("Nome");\n  const [modelQuery, setModelQuery] = useState("");\n  const [modelSort, setModelSort] = useState<"Nome" | "Mais itens">("Nome");\n', "Ares estados")
    old_filtered = '''  const filtered = useMemo(() => {
    const value = query.trim().toLowerCase();
    return normalizedQuotes.filter((quote) => (statusFilter === "Todas" || quote.status === statusFilter) && (!value || `${quote.id} ${quote.client} ${quote.title}`.toLowerCase().includes(value)));
  }, [normalizedQuotes, query, statusFilter]);
'''
    new_filtered = '''  const filtered = useMemo(() => {
    const value = query.trim().toLowerCase();
    const scoped = normalizedQuotes.filter((quote) => (scope === "Finalizadas" ? finalQuoteStatuses.includes(quote.status) : !finalQuoteStatuses.includes(quote.status)) && (statusFilter === "Todas" || quote.status === statusFilter) && (!value || `${quote.id} ${quote.client} ${quote.title}`.toLowerCase().includes(value)));
    return [...scoped].sort((a, b) => sortMode === "Cliente" ? a.client.localeCompare(b.client, "pt-BR") : sortMode === "Valor" ? quoteTotal(b) - quoteTotal(a) : sortMode === "Validade" ? a.validity.localeCompare(b.validity) : normalizedQuotes.indexOf(a) - normalizedQuotes.indexOf(b));
  }, [normalizedQuotes, query, scope, sortMode, statusFilter]);
  const clientRows = useMemo(() => Array.from(new Set(quotes.map((quote) => quote.client).filter(Boolean))).map((client) => ({ client, quotes: quotes.filter((quote) => quote.client === client) })).filter((item) => item.client.toLowerCase().includes(clientQuery.trim().toLowerCase())).sort((a, b) => clientSort === "Mais propostas" ? b.quotes.length - a.quotes.length : a.client.localeCompare(b.client, "pt-BR")), [clientQuery, clientSort, quotes]);
  const visibleModels = useMemo(() => [...models.filter((model) => `${model.name} ${model.title}`.toLowerCase().includes(modelQuery.trim().toLowerCase()))].sort((a, b) => modelSort === "Mais itens" ? b.items.length - a.items.length : a.name.localeCompare(b.name, "pt-BR")), [modelQuery, modelSort, models]);
'''
    text = replace_once(text, old_filtered, new_filtered, "Ares filtros")
    text = text.replace('function newQuote(model?: QuoteModel) { setEditing(blankQuote(model)); setSelectedId(""); setActive("Criar proposta"); }', 'function newQuote(model?: QuoteModel) { setEditing(blankQuote(model)); setSelectedId(""); setScope("Em andamento"); setActive("Criar proposta"); }')
    text = text.replace('    setSelectedId(normalized.id);\n    setEditing(null);', '    setSelectedId(normalized.id);\n    setScope(finalQuoteStatuses.includes(normalized.status) ? "Finalizadas" : "Em andamento");\n    setEditing(null);')
    old_main = '<section className={styles.listPane}><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cliente, proposta ou código" /></label><select className={styles.compactSelect} value={statusFilter} onChange={(event) => { setStatusFilter(event.target.value as QuoteStatus | "Todas"); setSelectedId(""); }}><option>Todas</option>{statusOptions.map((status) => <option key={status}>{status}</option>)}</select></div><div className={styles.recordList}>'
    new_main = '<section className={styles.listPane}><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cliente, proposta ou código" /></label><select className={styles.compactSelect} value={statusFilter} onChange={(event) => { setStatusFilter(event.target.value as QuoteStatus | "Todas"); setSelectedId(""); }}><option>Todas</option>{statusOptions.map((status) => <option key={status}>{status}</option>)}</select><select className={styles.compactSelect} value={sortMode} onChange={(event) => setSortMode(event.target.value as typeof sortMode)}><option>Mais recentes</option><option>Cliente</option><option>Valor</option><option>Validade</option></select></div><div className={styles.segmented}><button className={scope === "Em andamento" ? styles.segmentActive : ""} onClick={() => { setScope("Em andamento"); setStatusFilter("Todas"); setSelectedId(""); }}>Em andamento <span>{normalizedQuotes.filter((quote) => !finalQuoteStatuses.includes(quote.status)).length}</span></button><button className={scope === "Finalizadas" ? styles.segmentActive : ""} onClick={() => { setScope("Finalizadas"); setStatusFilter("Todas"); setSelectedId(""); }}>Finalizadas <span>{normalizedQuotes.filter((quote) => finalQuoteStatuses.includes(quote.status)).length}</span></button></div><div className={styles.recordList}>'
    text = replace_once(text, old_main, new_main, "Ares lista principal")
    old_clients = '    {active === "Clientes" ? <section className={styles.pageSheet}><div className={styles.pageHeading}><div><span className={styles.eyebrow}>Clientes</span><h2>Histórico de propostas</h2><p>Selecione um cliente para abrir sua versão mais recente.</p></div></div><div className={styles.directoryRows}>{Array.from(new Set(quotes.map((quote) => quote.client).filter(Boolean))).map((client) => { const clientQuotes = quotes.filter((quote) => quote.client === client); return <button key={client} onClick={() => { const quote = clientQuotes[0]; if (quote) { setSelectedId(quote.id); setActive("Propostas"); } }}><span className={styles.companyAvatar}>{client.slice(0, 2).toUpperCase()}</span><div><strong>{client}</strong><small>{clientQuotes.length} versão(ões)</small></div><Icon name="chevron" /></button>; })}</div></section> : null}\n'
    new_clients = '    {active === "Clientes" ? <section className={styles.pageSheet}><div className={styles.pageHeading}><div><span className={styles.eyebrow}>Clientes</span><h2>Histórico de propostas</h2><p>Selecione um cliente para abrir sua versão mais recente.</p></div></div><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={clientQuery} onChange={(event) => setClientQuery(event.target.value)} placeholder="Buscar cliente" /></label><select className={styles.compactSelect} value={clientSort} onChange={(event) => setClientSort(event.target.value as typeof clientSort)}><option>Nome</option><option>Mais propostas</option></select></div><div className={styles.directoryRows}>{clientRows.map(({ client, quotes: clientQuotes }) => <button key={client} onClick={() => { const quote = clientQuotes[0]; if (quote) { setSelectedId(quote.id); setScope(finalQuoteStatuses.includes(quote.status) ? "Finalizadas" : "Em andamento"); setActive("Propostas"); } }}><span className={styles.companyAvatar}>{client.slice(0, 2).toUpperCase()}</span><div><strong>{client}</strong><small>{clientQuotes.length} versão(ões)</small></div><Icon name="chevron" /></button>)}{!clientRows.length ? <EmptyState icon="search" title="Nenhum cliente encontrado" description="Altere a busca ou a classificação." /> : null}</div></section> : null}\n'
    text = replace_once(text, old_clients, new_clients, "Ares clientes")
    old_models = '    {active === "Modelos" ? <section className={styles.pageSheet}><div className={styles.pageHeading}><div><span className={styles.eyebrow}>Modelos</span><h2>Comece com uma estrutura pronta</h2></div></div><div className={styles.templateGrid}>{models.map((model) => <article key={model.id}><div className={styles.templateIcon}><Icon name="document" /></div><h3>{model.name}</h3><p>{model.items.length} itens</p><div><button className={styles.secondaryButton} onClick={() => newQuote(model)}>Usar modelo</button><button className={styles.iconButton} aria-label={`Remover modelo ${model.name}`} onClick={() => removeModel(model)}><Icon name="trash" /></button></div></article>)}</div></section> : null}\n'
    new_models = '    {active === "Modelos" ? <section className={styles.pageSheet}><div className={styles.pageHeading}><div><span className={styles.eyebrow}>Modelos</span><h2>Comece com uma estrutura pronta</h2></div></div><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={modelQuery} onChange={(event) => setModelQuery(event.target.value)} placeholder="Buscar modelo" /></label><select className={styles.compactSelect} value={modelSort} onChange={(event) => setModelSort(event.target.value as typeof modelSort)}><option>Nome</option><option>Mais itens</option></select></div><div className={styles.templateGrid}>{visibleModels.map((model) => <article key={model.id}><div className={styles.templateIcon}><Icon name="document" /></div><h3>{model.name}</h3><p>{model.items.length} itens</p><div><button className={styles.secondaryButton} onClick={() => newQuote(model)}>Usar modelo</button><button className={styles.iconButton} aria-label={`Remover modelo ${model.name}`} onClick={() => removeModel(model)}><Icon name="trash" /></button></div></article>)}{!visibleModels.length ? <EmptyState icon="search" title="Nenhum modelo encontrado" description="Altere a busca ou a classificação." /> : null}</div></section> : null}\n'
    text = replace_once(text, old_models, new_models, "Ares modelos")
    path.write_text(text, encoding="utf-8")


# ARTEMIS
path = Path("components/workspaces/phase-four/ArtemisApp.tsx")
text = path.read_text(encoding="utf-8")
if 'const [tableQuery, setTableQuery] = useState("");' not in text:
    text = replace_once(text, '  const [categoryFilter, setCategoryFilter] = useState("Todas");\n', '  const [categoryFilter, setCategoryFilter] = useState("Todas");\n  const [menuAvailability, setMenuAvailability] = useState<"Todos" | "Disponíveis" | "Indisponíveis">("Todos");\n  const [menuSort, setMenuSort] = useState<"Nome" | "Preço menor" | "Preço maior">("Nome");\n  const [tableQuery, setTableQuery] = useState("");\n  const [tableFilter, setTableFilter] = useState<TableStatus | "Todos">("Todos");\n  const [tableSort, setTableSort] = useState<"Número" | "Situação" | "Mais itens">("Número");\n  const [kitchenQuery, setKitchenQuery] = useState("");\n  const [kitchenFilter, setKitchenFilter] = useState<KitchenTicket["state"] | "Todos">("Todos");\n  const [kitchenSort, setKitchenSort] = useState<"Mais antigos" | "Mesa" | "Situação">("Mais antigos");\n  const [historyQuery, setHistoryQuery] = useState("");\n  const [historySort, setHistorySort] = useState<"Mais recentes" | "Maior valor" | "Mesa">("Mais recentes");\n', "Artemis estados")
    old_menu = '  const filteredMenu = useMemo(() => { const value = menuQuery.trim().toLowerCase(); return menu.filter((item) => (categoryFilter === "Todas" || item.category === categoryFilter) && (!value || `${item.name} ${item.category}`.toLowerCase().includes(value))); }, [categoryFilter, menu, menuQuery]);\n'
    new_menu = '''  const filteredMenu = useMemo(() => { const value = menuQuery.trim().toLowerCase(); const scoped = menu.filter((item) => (categoryFilter === "Todas" || item.category === categoryFilter) && (menuAvailability === "Todos" || (menuAvailability === "Disponíveis" ? item.active : !item.active)) && (!value || `${item.name} ${item.category}`.toLowerCase().includes(value))); return [...scoped].sort((a, b) => menuSort === "Preço menor" ? a.price - b.price : menuSort === "Preço maior" ? b.price - a.price : a.name.localeCompare(b.name, "pt-BR")); }, [categoryFilter, menu, menuAvailability, menuQuery, menuSort]);
  const visibleTables = useMemo(() => { const value = tableQuery.trim().toLowerCase(); const scoped = tables.filter((table) => (tableFilter === "Todos" || table.status === tableFilter) && (!value || `mesa ${table.id} ${table.waiter ?? ""} ${table.status}`.toLowerCase().includes(value))); return [...scoped].sort((a, b) => tableSort === "Situação" ? tableStatusOrder.indexOf(a.status) - tableStatusOrder.indexOf(b.status) : tableSort === "Mais itens" ? b.items.length - a.items.length : a.id - b.id); }, [tableFilter, tableQuery, tableSort, tables]);
  const visibleTickets = useMemo(() => { const value = kitchenQuery.trim().toLowerCase(); const scoped = tickets.filter((ticket) => (kitchenFilter === "Todos" || ticket.state === kitchenFilter) && (!value || `${ticket.id} mesa ${ticket.tableId} ${ticket.items.map((item) => item.name).join(" ")}`.toLowerCase().includes(value))); return [...scoped].sort((a, b) => kitchenSort === "Mesa" ? a.tableId - b.tableId : kitchenSort === "Situação" ? kitchenStatusOrder.indexOf(a.state) - kitchenStatusOrder.indexOf(b.state) : tickets.indexOf(a) - tickets.indexOf(b)); }, [kitchenFilter, kitchenQuery, kitchenSort, tickets]);
  const visibleHistory = useMemo(() => { const value = historyQuery.trim().toLowerCase(); const scoped = history.filter((item) => !value || `${item.id} ${item.place} ${item.summary ?? ""}`.toLowerCase().includes(value)); return [...scoped].sort((a, b) => historySort === "Maior valor" ? b.total - a.total : historySort === "Mesa" ? a.place.localeCompare(b.place, "pt-BR") : history.indexOf(a) - history.indexOf(b)); }, [history, historyQuery, historySort]);
'''
    text = replace_once(text, old_menu, new_menu, "Artemis listas")
    old_floor = '<section className={styles.floorSheet}><div className={styles.pageHeading}><div><span className={styles.eyebrow}>Turno atual</span><h2>Mapa do salão</h2><p>Escolha uma mesa; nenhuma abre automaticamente.</p></div></div><div className={styles.floorMap}>{tables.map((table) =>'
    new_floor = '<section className={styles.floorSheet}><div className={styles.pageHeading}><div><span className={styles.eyebrow}>Turno atual</span><h2>Mapa do salão</h2><p>Escolha uma mesa; nenhuma abre automaticamente.</p></div></div><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={tableQuery} onChange={(event) => setTableQuery(event.target.value)} placeholder="Mesa, responsável ou situação" /></label><select className={styles.compactSelect} value={tableFilter} onChange={(event) => setTableFilter(event.target.value as TableStatus | "Todos")}><option>Todos</option>{tableStatusOrder.map((status) => <option key={status}>{status}</option>)}</select><select className={styles.compactSelect} value={tableSort} onChange={(event) => setTableSort(event.target.value as typeof tableSort)}><option>Número</option><option>Situação</option><option>Mais itens</option></select></div><div className={styles.floorMap}>{visibleTables.map((table) =>'
    text = replace_once(text, old_floor, new_floor, "Artemis salão")
    old_kitchen = '    {active === "Cozinha" ? <section className={styles.pageSheet}><div className={styles.kitchenTable}>{tickets.map((ticket) =>'
    new_kitchen = '    {active === "Cozinha" ? <section className={styles.pageSheet}><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={kitchenQuery} onChange={(event) => setKitchenQuery(event.target.value)} placeholder="Pedido, mesa ou item" /></label><select className={styles.compactSelect} value={kitchenFilter} onChange={(event) => setKitchenFilter(event.target.value as KitchenTicket["state"] | "Todos")}><option>Todos</option>{kitchenStatusOrder.map((status) => <option key={status}>{status}</option>)}</select><select className={styles.compactSelect} value={kitchenSort} onChange={(event) => setKitchenSort(event.target.value as typeof kitchenSort)}><option>Mais antigos</option><option>Mesa</option><option>Situação</option></select></div><div className={styles.kitchenTable}>{visibleTickets.map((ticket) =>'
    text = replace_once(text, old_kitchen, new_kitchen, "Artemis cozinha")
    old_card = '<div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={menuQuery} onChange={(event) => setMenuQuery(event.target.value)} placeholder="Buscar item ou categoria" /></label><select className={styles.compactSelect} value={categoryFilter} onChange={(event) => setCategoryFilter(event.target.value)}>{categories.map((category) => <option key={category}>{category}</option>)}</select></div>'
    new_card = '<div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={menuQuery} onChange={(event) => setMenuQuery(event.target.value)} placeholder="Buscar item ou categoria" /></label><select className={styles.compactSelect} value={categoryFilter} onChange={(event) => setCategoryFilter(event.target.value)}>{categories.map((category) => <option key={category}>{category}</option>)}</select><select className={styles.compactSelect} value={menuAvailability} onChange={(event) => setMenuAvailability(event.target.value as typeof menuAvailability)}><option>Todos</option><option>Disponíveis</option><option>Indisponíveis</option></select><select className={styles.compactSelect} value={menuSort} onChange={(event) => setMenuSort(event.target.value as typeof menuSort)}><option>Nome</option><option>Preço menor</option><option>Preço maior</option></select></div>'
    text = replace_once(text, old_card, new_card, "Artemis cardápio")
    old_history = '    {active === "Histórico" ? <section className={styles.pageSheet}><div className={styles.directoryRows}>{history.map((item) =>'
    new_history = '    {active === "Histórico" ? <section className={styles.pageSheet}><div className={styles.listToolbar}><label className={styles.inputSearch}><Icon name="search" /><input value={historyQuery} onChange={(event) => setHistoryQuery(event.target.value)} placeholder="Mesa, comanda ou item" /></label><select className={styles.compactSelect} value={historySort} onChange={(event) => setHistorySort(event.target.value as typeof historySort)}><option>Mais recentes</option><option>Maior valor</option><option>Mesa</option></select></div><div className={styles.directoryRows}>{visibleHistory.map((item) =>'
    text = replace_once(text, old_history, new_history, "Artemis histórico")
    text += '\nconst tableStatusOrder: TableStatus[] = ["Livre", "Em atendimento", "Na cozinha", "Pronto"];\nconst kitchenStatusOrder: KitchenTicket["state"][] = ["Novo", "Preparando", "Pronto"];\n'
    path.write_text(text, encoding="utf-8")
